/* Generated by Yosys 0.67+24 (git sha1 0e82bbefe, GNU /usr/bin/c++ 13.3.0) */

module alu(a, b, c, s, o);
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  input [2:0] s;
  wire [2:0] s;
  output o;
  wire o;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  INV_X1 _16_ (
    .A(s[0]),
    .ZN(_14_)
  );
  INV_X1 _17_ (
    .A(s[2]),
    .ZN(_15_)
  );
  INV_X1 _18_ (
    .A(s[1]),
    .ZN(_00_)
  );
  OR2_X1 _19_ (
    .A1(b),
    .A2(c),
    .ZN(_01_)
  );
  OAI21_X1 _20_ (
    .A(a),
    .B1(c),
    .B2(b),
    .ZN(_02_)
  );
  NAND2_X1 _21_ (
    .A1(s[0]),
    .A2(a),
    .ZN(_03_)
  );
  AOI21_X1 _22_ (
    .A(_15_),
    .B1(_02_),
    .B2(_14_),
    .ZN(_04_)
  );
  NAND2_X1 _23_ (
    .A1(_03_),
    .A2(_04_),
    .ZN(_05_)
  );
  AND2_X1 _24_ (
    .A1(b),
    .A2(c),
    .ZN(_06_)
  );
  OAI211_X1 _25_ (
    .A(_15_),
    .B(_01_),
    .C1(_06_),
    .C2(s[0]),
    .ZN(_07_)
  );
  AOI21_X1 _26_ (
    .A(_00_),
    .B1(_06_),
    .B2(_14_),
    .ZN(_08_)
  );
  AND2_X1 _27_ (
    .A1(_07_),
    .A2(_08_),
    .ZN(_09_)
  );
  XOR2_X1 _28_ (
    .A(b),
    .B(c),
    .Z(_10_)
  );
  AND2_X1 _29_ (
    .A1(_03_),
    .A2(_10_),
    .ZN(_11_)
  );
  OAI21_X1 _30_ (
    .A(s[2]),
    .B1(_03_),
    .B2(_10_),
    .ZN(_12_)
  );
  OAI21_X1 _31_ (
    .A(_07_),
    .B1(_11_),
    .B2(_12_),
    .ZN(_13_)
  );
  AOI22_X1 _32_ (
    .A1(_05_),
    .A2(_09_),
    .B1(_13_),
    .B2(_00_),
    .ZN(o)
  );
endmodule
